### ISSUE TITLE
How to incorporate grad_penalty in RaGAN?

### ISSUE THREAD

**Issue by crwsr124** [AlexiaJM/MaximumMarginGANs#2]
In the code, there is no grad_penalty for RaGAN. Can I still use the grad of y0/x_both?

**Comment by AlexiaJM** [comment]
Hi,

You can still use --grad_penalty. It's applied to C(x_both) and yes that is okay because gradient penalty can be applied to either C(x_real) only, C(x_fake) only, C(x_both) only, or even C(x_real) and C(x_fake); in practice, it makes little to no difference whatever approach you use, as long as one critic is gradient penalized the other also end up having lower gradients. Feel free to try the different choices if you want to verify.
